"""
-------------------------------------------------------------------------
PROJECT  : Python Data Architecture
FILE     : Person_Data.py
AUTHOR   : omegazyph
CREATED  : 12-31-2025
UPDATED  : 12-31-2025
DESCRIPTION: Implementation of a Python Dataclass for structured object 
             management and automated equality comparison.
-------------------------------------------------------------------------
"""

from dataclasses import dataclass

# The @dataclass decorator eliminates the need for manual __init__ and __repr__
@dataclass
class Person:
    name: str  # String representation of user name
    age: int   # Integer representation of age
    job: str   # String representation of occupation

# Creating instances (Objects) of the Person class
# Logic: Values are passed into the auto-generated __init__ method.
person1 = Person(name="Alice", age=30, job="Engineer")
person2 = Person(name="Alice", age=31, job="Engineer")

# The __eq__ method generated by @dataclass compares the values of the fields.
# Since 30 != 31, this evaluates to False.
print(f"Comparison Result (person1 == person2): {person1 == person2}")